# Name of Workflow
name: My Test Workflow

# Define Conditions for when the workflow should run
on: [push, pull_request]

# Define Jobs that run in parallel, each in its own runner in sequence
jobs:

    # Job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, World!"